<?php


namespace App\Tests\Unit;

use App\Entity\Article;
use App\Entity\User;
use PHPUnit\Framework\TestCase;

class ArticleTest extends TestCase
{
    private $Article;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->Article = new Article();
    }

    public function testGetName()
    {
        $value = "stephen";
        // insert in suer object
        $response = $this->Article->setName($value);

        self::assertInstanceOf(Article::class, $response);
        // on attend à recevoir le name de l'article
        self::assertEquals($value, $this->Article->getName());
    }
    public function testGetContent()
    {
        $value = "blabla";
        // insert in suer object
        $response = $this->Article->setContent($value);

        self::assertInstanceOf(Article::class, $response);
        // on attend à recevoir le name de l'article
        self::assertEquals($value, $this->Article->getContent());
    }
    public function testGetAuthor()
    {
        $value = new User();
        // insert in suer object
        $response = $this->Article->setAuthor($value);

        self::assertInstanceOf(Article::class, $response);
        self::assertInstanceOf(User::class, $this->Article->getAuthor());
    }
}
